version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-cleanarch
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ['/app/bin/consumer']

  publisher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-publisher
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: ['/app/bin/publisher']
